export const camera: string;
export const stage: string;
export const box: string;
export const up: string;
export const down: string;
export const left: string;
export const right: string;
export const front: string;
export const back: string;
